"""create tables

Revision ID: 123d6667a099
Revises: c4f1de9fd1e1
Create Date: 2023-08-09 11:25:29.596925

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '123d6667a099'
down_revision = 'c4f1de9fd1e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_info',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('raw_file', sa.LargeBinary(), nullable=False),
    sa.Column('file_type', sa.Enum('PDF', 'JPEG', 'JPG', 'PNG', name='filetype'), nullable=False),
    sa.Column('processed_files', postgresql.ARRAY(sa.LargeBinary()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='test_table_pkey')
    )
    op.drop_table('media_info')
    # ### end Alembic commands ###
